version: '3.8'
services:
  backend:
    image: backend:latest
    ports:
      - "3000:3000"
    depends_on:
      - database
  frontend:
    image: frontend:latest
    ports:
      - "80:80"
  database:
    image: postgres:14.1
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=konecta

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
        - "5050:80"
    depends_on:
        - database
